# Generated by Django 4.2.4 on 2023-08-06 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_student_stu_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stu_id',
        ),
    ]
