# Generated by Django 4.2.4 on 2023-08-06 14:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_student_stu_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterMaster',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('chapter_name', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('medium', models.TextField(blank=True, null=True)),
                ('chapter_no', models.IntegerField(blank=True, null=True)),
                ('std', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chapter_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Physics11GujChapters',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('chapters', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'physics_11_guj_chapters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StandardMaster',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('std', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'standard_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectMaster',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subject_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_date', models.DateField()),
                ('chapters', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('total_marks', models.IntegerField()),
                ('standard', models.IntegerField()),
                ('medium', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
