# Generated by Django 4.2.4 on 2023-08-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_chaptermaster_physics11gujchapters_standardmaster_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Physics11GujChapters',
        ),
        migrations.DeleteModel(
            name='StandardMaster',
        ),
        migrations.DeleteModel(
            name='SubjectMaster',
        ),
    ]
