# Generated by Django 4.2.4 on 2023-08-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_physics11gujchapters_delete_standardmaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_date', models.DateField()),
                ('chapters', models.JSONField(default=dict)),
                ('total_marks', models.IntegerField()),
                ('standard', models.IntegerField()),
                ('medium', models.TextField()),
            ],
            options={
                'db_table': 'test_data',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='medium',
        ),
        migrations.AddField(
            model_name='student',
            name='standard',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
