# Generated by Django 4.2.4 on 2023-08-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.BigIntegerField()),
                ('test_id', models.BigIntegerField()),
                ('total_marks', models.IntegerField(blank=True, null=True)),
                ('obtained', models.IntegerField(blank=True, null=True)),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('created_ts', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_test_results',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
    ]
