# Generated by Django 4.2.7 on 2023-12-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_studenttestresults_alter_student_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardMaster',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('std', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'standard_master',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': True},
        ),
    ]
